### ISSUE TITLE
Problem with deployment

### ISSUE THREAD

**Issue by bkostrowiecki** [krybicka/django-authapp#1]
Hi there,

I'm very impressed by your work. Simple and elegant.

But I have a problem with deploying this app to any free hosting. Can you consider rewriting it in PHP to provide support for wider spectrum of free services?

Best regards

**Comment by krybicka** [comment]
Hello,

It's very pleasant to see comments like this. I spent some time on learning python/django and coding  this app so I'm happy that someone appreciate my work!

Unfortunately I'm not a huge fan of PHP - maybe you will rewrite it, then we can compare our apps? 

In fact, deployment was the most difficult thing during 'creating process', so I understand the your problem. Earlier I tried heliohost.org but it doesn't support static files. If you'll try again I recommend pythonanywhere.com hosting :)

Best wishes
